### ISSUE TITLE
Add Taplo TOML Formatting and Verification for pyproject.toml

### ISSUE THREAD

**Issue by smorin** [smorin/py-launch-blueprint#35]
Title: Add Taplo TOML Formatting and Verification for pyproject.toml

**Background**
We need to implement automated TOML formatting and validation using Taplo to ensure consistent formatting and correctness of our pyproject.toml file. This will help maintain clean configuration files and catch potential issues early.

**Implementation Tasks**

1. Taplo Integration:
   - Add Taplo configuration
   - Setup pre-commit hook for Taplo
   - Configure GitHub Action for validation
   - Add format verification in CI pipeline

2. Configuration Setup:
   - Create `.taplo.toml` configuration file:
     ```toml
     [formatting]
     align_entries = true
     array_auto_expand = true
     column_width = 80
     indent_string = "    "
     ```
   - Add Taplo to development dependencies
   - Configure Taplo for pyproject.toml specifics

3. Add Just Commands:
   ```justfile
   format-toml:
       taplo format pyproject.toml
   
   check-toml:
       taplo check pyproject.toml
   ```

4. CI Integration:
   ```yaml
   - name: Check TOML formatting
     run: |
       taplo check pyproject.toml
   ```

5. Pre-commit Setup:
   ```yaml
   - repo: https://github.com/taplo-tools/taplo
     rev: release-cli-v0.8.1
     hooks:
       - id: taplo-format
         files: pyproject.toml
   ```

6. Documentation:
   - Add Taplo usage to README
   - Document format verification process
   - Add configuration explanation
   - Include troubleshooting guide

**Success Criteria**
- Automated TOML formatting working
- CI verification passing
- Pre-commit hook functioning
- Clear documentation available
- Just commands working

**Testing Requirements**
- Test format command
- Verify CI integration
- Check pre-commit functionality
- Validate configuration options
- Test error reporting

Please review the approach before implementation.
